[funds_filters]
# Names of the funds to be included. If empty, includes all
include = []

# Names of funds to exclude. If empty, does not exclude any. Excludes funds after
# including the ones selected above.
exclude = []

# Funds with volatility above this threshold will be excluded
volatility_threshold = 0.05

[portfolio]
number_of_funds = 6      # Number of funds to consider for the portfolio
from_date = "2021-01-01" # Start date to consider for the time series
to_date = "2023-01-01"   # End date to consider for the time series
split_granularity = 0.1  # Minimum percentage of a split. Should divide 1 into equal parts.
